#! /bin/bash

###################################################
############## TE Phylogenetic Trees ##############
###################################################
genome=~/yuyun/genome_data/161010_Chinese_Spring_v1.0_pseudomolecules_parts.fasta
mp=mergeTFBS_PE_summits.filter.p10.bed

#### full length
TE=~/yuyun/genome_data/TE_annotation/LTRharvest/CS_TE_LTR.fl.repeat_region.bed
for i in RLG_famc13 RLC_famc1.4 RLG_famc7.3
do
{
    grep $i -w $TE | bedtools intersect -a - -b merge_peaks_w_motifs.bed -wa | sort -u | bedtools sort -i - |\
        awk '{if($1~/A/)print $1"\t"$2"\t"$3"\t"$4"_"NR"_A_peak";\
              else if($1~/B/)print $1"\t"$2"\t"$3"\t"$4"_"NR"_B_peak";\
              else if($1~/D/)print $1"\t"$2"\t"$3"\t"$4"_"NR"_D_peak"}' > ${i}.peak.fl.bed
    grep $i -w $TE | bedtools intersect -a - -b $mp -wa -v | sort -u | bedtools sort -i - |\
        awk '{if($1~/A/)print $1"\t"$2"\t"$3"\t"$4"_"NR"_A_nonpeak";\
              else if($1~/B/)print $1"\t"$2"\t"$3"\t"$4"_"NR"_B_nonpeak";\
              else if($1~/D/)print $1"\t"$2"\t"$3"\t"$4"_"NR"_D_nonpeak"}' > ${i}.nonpeak.fl.bed

    shuf -n 200 ${i}.peak.fl.bed | bedtools getfasta -fi $genome -bed - -nameOnly > ${i}.peak.fl.fa
    shuf -n 200 ${i}.nonpeak.fl.bed | bedtools getfasta -fi $genome -bed - -nameOnly > ${i}.nonpeak.fl.fa
    grep '>' ${i}.peak.fl.fa | sed 's/>//' | awk '{print $1,$1}' | sed 's/ .*_[0-9]*_/ /' > ${i}.fl.anno
    grep '>' ${i}.nonpeak.fl.fa | sed 's/>//' | awk '{print $1,$1}' | sed 's/ .*_[0-9]*_/ /'  >> ${i}.fl.anno
    grep '>' ${i}.peak.fl.fa | sed 's/>//' | awk '{print $1,$1}' | sed 's/ .*_[0-9]*_/ /;s/_peak$//' > ${i}.fl.anno2
    grep '>' ${i}.nonpeak.fl.fa | sed 's/>//' | awk '{print $1,$1}' | sed 's/ .*_[0-9]*_/ /;s/_nonpeak$//'  >> ${i}.fl.anno2

    cat ${i}.*.fl.fa > ${i}.fl.fa
    mafft --thread 10 --quiet ${i}.fl.fa > ${i}.mafft.fl.fa
    fasttree -nt -quiet ${i}.mafft.fl.fa > ${i}.mafft.fl.tree
    echo finished_${i}
}&
wait
awk '{if($2=="A_peak")print $1,"1 0 0 4";else if($2=="B_peak")print $1,"0 2 0 4";else if($2=="D_peak")print $1,"0 0 3 4";else if($2=="A_nonpeak")print $1,"1 0 0 0";else if($2=="B_nonpeak")print $1,"0 2 0 0";else if($2=="D_nonpeak")print $1,"0 0 3 0"}' ${i}.fl.anno > ${i}.fl.heatmap
done

#sed '/^>/ s/^>/>R_/' r.fa > ../r.fa