#! /bin/bash

curated=''  thread=''  log_num=''  outdir=''

usage() {
  echo "Usage: run TE detect programs"
    echo "  -h        help"
    echo "  -p <str>  program name, including EDTA[edta], RepeatModeler[rm2], ClariTE[clt], HiTE[hite]"
    echo "  -g <str>  reference genome sequence"
    echo "  -c <str>  curated TE library"
    echo "  -t <str>  thread number"
    echo "  -n <str>  log file number"
    echo "  -o <str>  output directory"
  exit 1
}

if [ $# -eq 0 ]; then
  usage
fi

while getopts "h:p:g:c:t:n:o:" opt; do
  case $opt in
    h) usage
      ;;
    p) prog=$OPTARG
      ;;
    g) genome=$OPTARG
      ;;
    c) curated=$OPTARG
      ;;
    t) thread=$OPTARG
      ;;
    n) log_num=$OPTARG
      ;;
    o) outdir=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

if [ $prog == "edta" ]; then
  nohup perl ~/transposon/tools/EDTA/EDTA.pl \
    --genome genome \
    --overwrite 0 \
    --sensitive 1 \
    --anno 1 \
    --threads thread > log_num.log 2>&1 &
elif [ $prog == "hite" ]; then
  cd ~/transposon/tools/HiTE
  python main.py \
    --genome genome \
    --outdir outdir \
    --thread thread \
    --domain 1 \
    --recover 1 \
    --annotate 1 \
    --intact_anno 1 \
    --BM_EDTA 1 \
    --EDTA_home /data1/home/dazheng/transposon/tools/EDTA \
    --coverage_threshold 0.8 \
    --is_wicker 1
fi

