#! /bin/bash

# This script is used to copy the fastq files based on size

## $1: /file/location
## $2: /path/to/destination
## $3: files

files=$3
size=${#files[@]}
for (( i = 0; i < size; i++ )); do
  cp -ax "$1/${files[i]}" "$2"
done

dicts=(CRR876521 CRR876522)
n=${#dicts[@]}
for (( i = 0; i < n; i++ )); do
    md5sum "${dicts[i]}/${dicts[i]}_f1.fastq.gz" >> md5sum.txt &
    md5sum "${dicts[i]}/${dicts[i]}_r2.fastq.gz" >> md5sum.txt &
    wait
done



mapfile -t dicts < cklist.txt
n=${#dicts[@]}
for (( i = 0; i < n; i++ )); do
    md5sum "${dicts[i]}" >> "${dicts[i]}.md5" &
    if [ $((i % 6)) -eq 5 ]; then
        wait
    fi
done
wait